security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /accountHolder/logout
            anonymous: true
            security: true

    access_control:
        - { path: ^/accountHolder, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        webservice:
            id: psamatt.expenditure.webservice_user_provider

    encoders:
        Psamatt\Pecunia\Application\ACL\User: sha512