index:
    path:  /
    defaults: { _controller: PsamattExpenditureBundle:User:login }
    methods:  [GET]

login:
    path:  /login
    defaults: { _controller: PsamattExpenditureBundle:User:login }
    methods:  [GET]

login_check:
    pattern:   /login_check

logout:
    pattern:   /admin/logout

register:
    path:  /profile/new
    defaults: { _controller: PsamattExpenditureBundle:User:new }
    methods:  [GET|POST]

admin_homepage:
    path:  /admin
    defaults: { _controller: PsamattExpenditureBundle:Default:index }
    methods:  [GET]

profile_edit:
    path:  /admin/profile/edit
    defaults: { _controller: PsamattExpenditureBundle:User:edit }
    methods:  [GET|POST]

profile_change_password:
    path:  /admin/profile/password/change
    defaults: { _controller: PsamattExpenditureBundle:User:changePassword }
    methods:  [POST]

admin_import:
    path:  /admin/import/{year}/{month}
    defaults: { _controller: PsamattExpenditureBundle:Import:save }
    methods:  [POST]

admin_expenditure_paid:
    path:  /admin/month/{headerID}/expenditure/{expenditureID}/paid
    defaults: { _controller: PsamattExpenditureBundle:MonthExpenditure:paid }
    requirements:
        headerID: \d+
        expenditureID: \d+
    methods:  [POST]

admin_expenditure_delete:
    path:  /admin/month/{headerID}/expenditure/{expenditureID}/delete
    defaults: { _controller: PsamattExpenditureBundle:MonthExpenditure:delete }
    requirements:
        headerID: \d+
        expenditureID: \d+
    methods:  [POST]

admin_expenditure_save:
    path:  /admin/month/{headerID}/expenditure/save
    defaults: { _controller: PsamattExpenditureBundle:MonthExpenditure:save }
    requirements:
        headerID: \d+
        expenditureID: \d+
    methods:  [POST]

admin_payments:
    path:  /admin/month/default/{defaultID}
    defaults: { _controller: PsamattExpenditureBundle:DefaultPayment:view, defaultID: 0 }
    requirements:
        defaultID: \d+
    methods:  [GET]

admin_payments_delete:
    path:  /admin/month/default/{defaultID}/delete
    defaults: { _controller: PsamattExpenditureBundle:DefaultPayment:delete }
    requirements:
        defaultID: \d+
    methods:  [GET]

admin_payments_save:
    path:  /admin/month/default/{defaultID}/save
    defaults: { _controller: PsamattExpenditureBundle:DefaultPayment:save }
    requirements:
        defaultID: \d+
    methods:  [POST]

admin_historic:
    path:  /admin/month/historic
    defaults: { _controller: PsamattExpenditureBundle:MonthHistoric:index }
    methods:  [GET]

admin_historic_view:
    path:  /admin/month/historic/{year}/{month}
    defaults: { _controller: PsamattExpenditureBundle:MonthHistoric:view }
    requirements:
        year: \d+
        month: \d+
    methods:  [GET]

admin_savings:
    path:  /admin/savings
    defaults: { _controller: PsamattExpenditureBundle:Saving:index }
    methods:  [GET]

admin_savings_save:
    path:  /admin/savings/{savingID}/save
    defaults: { _controller: PsamattExpenditureBundle:Saving:save }
    methods:  [POST]
    options:
        expose: true

admin_savings_add:
    path:  /admin/savings/{savingID}/money/add
    defaults: { _controller: PsamattExpenditureBundle:Saving:addMoney }
    requirements:
        savingID: \d+
    methods:  [POST]
    options:
        expose: true

admin_savings_delete:
    path:  /admin/savings/{savingID}/delete
    defaults: { _controller: PsamattExpenditureBundle:Saving:delete }
    requirements:
        savingID: \d+
    methods:  [POST]
    options:
        expose: true
