parameters:

    webservice_user_provider.class: Psamatt\ExpenditureBundle\Provider\UserProvider
    psamatt.expenditure.twig.extension.class: Psamatt\ExpenditureBundle\Twig\Extension\CarbonTwigExtension
    templateToExpenditure.transformer.class: Psamatt\ExpenditureBundle\DataTransformer\TemplateToExpenditure
    
    saving.service.class: Psamatt\ExpenditureBundle\Services\SavingService
    expenditureTemplate.service.class: Psamatt\ExpenditureBundle\Services\ExpenditureTemplateService
    
    saving.doctrine.orm.repository.class: Psamatt\ExpenditureBundle\Repository\Saving\DoctrineORMRepository
    expenditureTemplate.doctrine.orm.repository.class: Psamatt\ExpenditureBundle\Repository\ExpenditureTemplate\DoctrineORMRepository
services:

    templateToExpenditure.transformer:
        class: "%templateToExpenditure.transformer.class%"
        arguments: ~

    psamatt.expenditure.webservice_user_provider:
        class: "%webservice_user_provider.class%"
        arguments: [@doctrine.orm.entity_manager]
    
    psamatt.expenditure.twig.extension:
        class: "%psamatt.expenditure.twig.extension.class%"
        tags:
            - { name: twig.extension }

# ########################## Expenditure Template ##########################    
    expenditureTemplate.service:
        class: "%expenditureTemplate.service.class%"
        arguments: [@expenditureTemplate.repository, @event_dispatcher]
    
    expenditureTemplate.repository:
        alias: expenditureTemplate.doctrine.orm.repository
    
    expenditureTemplate.doctrine.orm.repository:
        class: "%expenditureTemplate.doctrine.orm.repository.class%"
        arguments: [@doctrine.orm.entity_manager]
        public: false

# ############################### Saving ################################  
    saving.service:
        class: "%saving.service.class%"
        arguments: [@saving.repository]
    
    saving.repository:
        alias: saving.doctrine.orm.repository
    
    saving.doctrine.orm.repository:
        class: "%saving.doctrine.orm.repository.class%"
        arguments: [@doctrine.orm.entity_manager]
        public: false