Psamatt\ExpenditureBundle\Entity\User:
  properties:
    email_address:
        - NotNull:
            message: Email Address must not be empty
        - NotBlank:
            message: Email Address must not be empty
        - Email:
            message: The email "{{ value }}" is not a valid email.
            checkMX: true
    paid_day:
        - Range:
            min: 1
            max: 31
            minMessage: The selected paid day must be at least the 1st
            maxMessage: You cannot have a paid day greater than 31